# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Admin(object):
    def setupUi(self, Admin):
        Admin.setObjectName("Admin")
        Admin.resize(347, 387)
        Admin.setMinimumSize(QtCore.QSize(347, 387))
        Admin.setMaximumSize(QtCore.QSize(347, 387))
        Admin.setStyleSheet("background-color: rgb(57, 130, 195);")
        self.centralwidget = QtWidgets.QWidget(Admin)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tbl_usuarios = QtWidgets.QTableWidget(self.centralwidget)
        self.tbl_usuarios.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbl_usuarios.sizePolicy().hasHeightForWidth())
        self.tbl_usuarios.setSizePolicy(sizePolicy)
        self.tbl_usuarios.setMaximumSize(QtCore.QSize(331, 321))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tbl_usuarios.setFont(font)
        self.tbl_usuarios.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tbl_usuarios.setAutoFillBackground(False)
        self.tbl_usuarios.setStyleSheet("")
        self.tbl_usuarios.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tbl_usuarios.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tbl_usuarios.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tbl_usuarios.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tbl_usuarios.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbl_usuarios.setTabKeyNavigation(False)
        self.tbl_usuarios.setAlternatingRowColors(False)
        self.tbl_usuarios.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tbl_usuarios.setTextElideMode(QtCore.Qt.ElideRight)
        self.tbl_usuarios.setShowGrid(True)
        self.tbl_usuarios.setGridStyle(QtCore.Qt.SolidLine)
        self.tbl_usuarios.setWordWrap(True)
        self.tbl_usuarios.setCornerButtonEnabled(True)
        self.tbl_usuarios.setColumnCount(4)
        self.tbl_usuarios.setObjectName("tbl_usuarios")
        self.tbl_usuarios.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_usuarios.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tbl_usuarios.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tbl_usuarios.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tbl_usuarios.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tbl_usuarios.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setCheckState(QtCore.Qt.Checked)
        self.tbl_usuarios.setItem(0, 3, item)
        self.tbl_usuarios.horizontalHeader().setVisible(True)
        self.tbl_usuarios.horizontalHeader().setHighlightSections(True)
        self.tbl_usuarios.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tbl_usuarios)
        self.horizontalWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_editar = QtWidgets.QPushButton(self.horizontalWidget)
        self.btn_editar.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_editar.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.btn_editar.setFont(font)
        self.btn_editar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_editar.setStyleSheet("*{\n"
"background-color: #6EC8DB;\n"
"border-radius: 15px;\n"
"color: white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#60afbf;\n"
"}")
        self.btn_editar.setDefault(True)
        self.btn_editar.setObjectName("btn_editar")
        self.horizontalLayout.addWidget(self.btn_editar)
        self.btn_excluir = QtWidgets.QPushButton(self.horizontalWidget)
        self.btn_excluir.setEnabled(True)
        self.btn_excluir.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_excluir.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.btn_excluir.setFont(font)
        self.btn_excluir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_excluir.setStyleSheet("*{\n"
"background-color: #df4759;\n"
"border-radius: 15px;\n"
"color: #fff;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #ba3847;\n"
"}\n"
"\n"
"")
        self.btn_excluir.setCheckable(False)
        self.btn_excluir.setChecked(False)
        self.btn_excluir.setDefault(True)
        self.btn_excluir.setObjectName("btn_excluir")
        self.horizontalLayout.addWidget(self.btn_excluir)
        self.verticalLayout.addWidget(self.horizontalWidget)
        self.btn_logout = QtWidgets.QPushButton(self.centralwidget)
        self.btn_logout.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_logout.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btn_logout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_logout.setStyleSheet("*{\n"
"background-color: #edd400;\n"
"border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #d1bc08;\n"
"}\n"
"\n"
"")
        self.btn_logout.setDefault(True)
        self.btn_logout.setObjectName("btn_logout")
        self.verticalLayout.addWidget(self.btn_logout, 0, QtCore.Qt.AlignHCenter)
        Admin.setCentralWidget(self.centralwidget)

        header = self.tbl_usuarios.horizontalHeader()
        header.setStyleSheet("::section {"
                                                        f"color: rgb(57, 130, 195);"
                                                        "}")
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(1, QtWidgets.QHeaderView.Stretch)
        header.setSectionResizeMode(2, QtWidgets.QHeaderView.Stretch)
        # header.setSectionResizeMode(4, QtWidgets.QHeaderView.ResizeToContents)

        self.retranslateUi(Admin)
        QtCore.QMetaObject.connectSlotsByName(Admin)

    def retranslateUi(self, Admin):
        _translate = QtCore.QCoreApplication.translate
        Admin.setWindowTitle(_translate("Admin", "Admin"))
        item = self.tbl_usuarios.verticalHeaderItem(0)
        item.setText(_translate("Admin", "New Row"))
        item = self.tbl_usuarios.horizontalHeaderItem(0)
        item.setText(_translate("Admin", "ID"))
        item = self.tbl_usuarios.horizontalHeaderItem(1)
        item.setText(_translate("Admin", "Nome"))
        item = self.tbl_usuarios.horizontalHeaderItem(2)
        item.setText(_translate("Admin", "Usuário"))
        item = self.tbl_usuarios.horizontalHeaderItem(3)
        item.setText(_translate("Admin", "Admin"))
        __sortingEnabled = self.tbl_usuarios.isSortingEnabled()
        self.tbl_usuarios.setSortingEnabled(False)
        self.tbl_usuarios.setSortingEnabled(__sortingEnabled)
        self.btn_editar.setText(_translate("Admin", "Editar"))
        self.btn_excluir.setText(_translate("Admin", "Excluir"))
        self.btn_logout.setText(_translate("Admin", "SAIR"))
