# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_logado.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Logado(object):
    def setupUi(self, TelaLogado):
        TelaLogado.setObjectName("TelaLogado")
        TelaLogado.resize(347, 369)
        TelaLogado.setMinimumSize(QtCore.QSize(347, 369))
        TelaLogado.setMaximumSize(QtCore.QSize(347, 369))
        TelaLogado.setStyleSheet("background-color: rgb(57, 130, 195);")
        TelaLogado.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(TelaLogado)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_nome = QtWidgets.QLabel(self.centralwidget)
        self.lbl_nome.setMaximumSize(QtCore.QSize(16777215, 80))
        self.lbl_nome.setStyleSheet("color:white;\n"
"font-size: 24px;")
        self.lbl_nome.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_nome.setObjectName("lbl_nome")
        self.verticalLayout.addWidget(self.lbl_nome)
        self.lbl_logado = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(1)
        self.lbl_logado.setFont(font)
        self.lbl_logado.setStyleSheet("color:white;\n"
"font-size: 24px;")
        self.lbl_logado.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lbl_logado.setObjectName("lbl_logado")
        self.verticalLayout.addWidget(self.lbl_logado)
        self.btn_logout = QtWidgets.QPushButton(self.centralwidget)
        self.btn_logout.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_logout.sizePolicy().hasHeightForWidth())
        self.btn_logout.setSizePolicy(sizePolicy)
        self.btn_logout.setMinimumSize(QtCore.QSize(150, 0))
        self.btn_logout.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_logout.setFont(font)
        self.btn_logout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_logout.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_logout.setStyleSheet("*{\n"
"background-color: #edd400;\n"
"border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #d1bc08;\n"
"}\n"
"\n"
"")
        self.btn_logout.setObjectName("btn_logout")
        self.verticalLayout.addWidget(self.btn_logout, 0, QtCore.Qt.AlignRight)
        TelaLogado.setCentralWidget(self.centralwidget)

        self.retranslateUi(TelaLogado)
        QtCore.QMetaObject.connectSlotsByName(TelaLogado)

    def retranslateUi(self, TelaLogado):
        _translate = QtCore.QCoreApplication.translate
        TelaLogado.setWindowTitle(_translate("TelaLogado", "Logado"))
        self.lbl_nome.setText(_translate("TelaLogado", "Olá, {nome}!"))
        self.lbl_logado.setText(_translate("TelaLogado", "Você está logado!"))
        self.btn_logout.setText(_translate("TelaLogado", "SAIR"))
