# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from .resources import resourcesLogin


class Ui_Login(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(347, 369)
        MainWindow.setMinimumSize(QtCore.QSize(347, 369))
        MainWindow.setMaximumSize(QtCore.QSize(347, 369))
        MainWindow.setStyleSheet("background-color: rgb(57, 130, 195);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(9, 9, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_login = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        self.lbl_login.setFont(font)
        self.lbl_login.setStyleSheet("font-size: 16pt;\n"
"color: white;")
        self.lbl_login.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_login.setObjectName("lbl_login")
        self.verticalLayout.addWidget(self.lbl_login)
        self.inputWidget = QtWidgets.QWidget(self.centralwidget)
        self.inputWidget.setObjectName("inputWidget")
        self.formLayout = QtWidgets.QFormLayout(self.inputWidget)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setObjectName("formLayout")
        self.usuario = QtWidgets.QLineEdit(self.inputWidget)
        self.usuario.setMaximumSize(QtCore.QSize(170, 50))
        self.usuario.setStyleSheet("*{\n"
"background-color: #fff;\n"
"border-radius: 15px;\n"
"padding: 5px;\n"
"padding-left: 7px;\n"
"}\n"
"QLineEdit:focus{\n"
"border: 2px solid #edd400;\n"
"}")
        self.usuario.setMaxLength(20)
        self.usuario.setObjectName("usuario")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.usuario)
        self.lbl_login_img = QtWidgets.QLabel(self.inputWidget)
        self.lbl_login_img.setMaximumSize(QtCore.QSize(30, 30))
        self.lbl_login_img.setText("")
        self.lbl_login_img.setPixmap(QtGui.QPixmap(":/icons/img/icoLogin.png"))
        self.lbl_login_img.setScaledContents(True)
        self.lbl_login_img.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_login_img.setObjectName("lbl_login_img")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_login_img)
        self.senha = QtWidgets.QLineEdit(self.inputWidget)
        self.senha.setMaximumSize(QtCore.QSize(170, 50))
        self.senha.setStyleSheet("*{\n"
"background-color: #fff;\n"
"border-radius: 15px;\n"
"padding: 5px;\n"
"padding-left: 7px;\n"
"}\n"
"QLineEdit:focus{\n"
"border: 2px solid #edd400;\n"
"}")
        self.senha.setMaxLength(20)
        self.senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.senha.setObjectName("senha")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.senha)
        self.lbl_senha_img = QtWidgets.QLabel(self.inputWidget)
        self.lbl_senha_img.setMaximumSize(QtCore.QSize(30, 30))
        self.lbl_senha_img.setText("")
        self.lbl_senha_img.setPixmap(QtGui.QPixmap(":/icons/img/icoSenha.png"))
        self.lbl_senha_img.setScaledContents(True)
        self.lbl_senha_img.setObjectName("lbl_senha_img")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_senha_img)
        self.verticalLayout.addWidget(self.inputWidget)
        self.lbl_erro = QtWidgets.QLabel(self.centralwidget)
        self.lbl_erro.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_erro.setFont(font)
        self.lbl_erro.setStyleSheet("color: rgb(237, 212, 0);")
        self.lbl_erro.setText("")
        self.lbl_erro.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_erro.setObjectName("lbl_erro")
        self.verticalLayout.addWidget(self.lbl_erro)
        self.btn_entrar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_entrar.setEnabled(True)
        self.btn_entrar.setMinimumSize(QtCore.QSize(100, 40))
        self.btn_entrar.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.btn_entrar.setFont(font)
        self.btn_entrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_entrar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_entrar.setAutoFillBackground(False)
        self.btn_entrar.setStyleSheet("*{\n"
"background-color: #6EC8DB;\n"
"border-radius: 15px;\n"
"color: white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#60afbf;\n"
"transition: 1s;\n"
"}")
        self.btn_entrar.setCheckable(False)
        self.btn_entrar.setChecked(False)
        self.btn_entrar.setAutoRepeat(False)
        self.btn_entrar.setDefault(True)
        self.btn_entrar.setFlat(False)
        self.btn_entrar.setObjectName("btn_entrar")
        self.verticalLayout.addWidget(self.btn_entrar, 0, QtCore.Qt.AlignHCenter)
        self.lbl_cadastro = QtWidgets.QLabel(self.centralwidget)
        self.lbl_cadastro.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lbl_cadastro.setObjectName("lbl_cadastro")
        self.verticalLayout.addWidget(self.lbl_cadastro)
        self.btn_cadastrar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cadastrar.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_cadastrar.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_cadastrar.setFont(font)
        self.btn_cadastrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cadastrar.setStyleSheet("*{\n"
"background-color: #edd400;\n"
"border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #d1bc08;\n"
"}\n"
"\n"
"")
        self.btn_cadastrar.setObjectName("btn_cadastrar")
        self.verticalLayout.addWidget(self.btn_cadastrar, 0, QtCore.Qt.AlignHCenter)
        MainWindow.setCentralWidget(self.centralwidget)

        self.usuario.returnPressed.connect(self.btn_entrar.click)
        self.senha.returnPressed.connect(self.btn_entrar.click)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.usuario, self.senha)
        MainWindow.setTabOrder(self.senha, self.btn_entrar)
        MainWindow.setTabOrder(self.btn_entrar, self.btn_cadastrar)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login"))
        self.lbl_login.setText(_translate("MainWindow", "Faça o seu login"))
        self.usuario.setPlaceholderText(_translate("MainWindow", "Usuário"))
        self.senha.setPlaceholderText(_translate("MainWindow", "Senha"))
        self.btn_entrar.setText(_translate("MainWindow", "Entrar"))
        self.lbl_cadastro.setText(_translate("MainWindow", "Não é cadastrado?"))
        self.btn_cadastrar.setText(_translate("MainWindow", "Cadastrar"))
