# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_cadastro.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TelaCadastro(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(335, 341)
        MainWindow.setMinimumSize(QtCore.QSize(335, 341))
        MainWindow.setMaximumSize(QtCore.QSize(335, 341))
        MainWindow.setStyleSheet("background-color: rgb(57, 130, 195);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_crie_conta = QtWidgets.QLabel(self.centralwidget)
        self.lbl_crie_conta.setGeometry(QtCore.QRect(70, 10, 201, 51))
        self.lbl_crie_conta.setStyleSheet("font-size: 20pt;\n"
"color: white;\n"
"font-weight: bold;")
        self.lbl_crie_conta.setObjectName("lbl_crie_conta")
        self.btn_cadastrar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cadastrar.setGeometry(QtCore.QRect(120, 202, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_cadastrar.setFont(font)
        self.btn_cadastrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cadastrar.setStyleSheet("background-color: rgb(237, 212, 0);\n"
"border-radius: 15px;")
        self.btn_cadastrar.setDefault(True)
        self.btn_cadastrar.setObjectName("btn_cadastrar")
        self.usuario = QtWidgets.QLineEdit(self.centralwidget)
        self.usuario.setGeometry(QtCore.QRect(80, 70, 181, 31))
        self.usuario.setStyleSheet("border-radius: 10px;\n"
"background-color:white;\n"
"padding: 4px;\n"
"padding-left: 7px;\n"
"")
        self.usuario.setObjectName("usuario")
        self.senha = QtWidgets.QLineEdit(self.centralwidget)
        self.senha.setGeometry(QtCore.QRect(80, 130, 181, 31))
        self.senha.setStyleSheet("border-radius: 10px;\n"
"background-color:white;\n"
"padding: 4px;\n"
"padding-left: 7px;")
        self.senha.setObjectName("senha")
        self.senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lbl_msg = QtWidgets.QLabel(self.centralwidget)
        self.lbl_msg.setGeometry(QtCore.QRect(20, 246, 291, 31))
        self.lbl_msg.setStyleSheet("color: rgb(237, 212, 0);;\n"
"font-size: 13pt;\n"
"font-weight: bold;\n"
"")
        self.lbl_msg.setText("")
        self.lbl_msg.setObjectName("lbl_msg")
        self.btn_voltar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_voltar.setGeometry(QtCore.QRect(120, 280, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_voltar.setFont(font)
        self.btn_voltar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_voltar.setStyleSheet("background-color: #6EC8DB;\n"
"color:white;\n"
"border-radius: 15px;\n"
"")
        self.btn_voltar.setObjectName("btn_voltar")
        self.lbl_erro = QtWidgets.QLabel(self.centralwidget)
        self.lbl_erro.setGeometry(QtCore.QRect(48, 167, 241, 31))
        self.lbl_erro.setStyleSheet("color: rgb(237, 212, 0);;\n"
"font-size: 13pt;\n"
"font-weight: bold;\n"
"")
        self.lbl_erro.setText("")
        self.lbl_erro.setObjectName("lbl_erro")
        self.lbl_crie_conta.raise_()
        self.btn_cadastrar.raise_()
        self.usuario.raise_()
        self.senha.raise_()
        self.btn_voltar.raise_()
        self.lbl_erro.raise_()
        self.lbl_msg.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.usuario, self.senha)
        MainWindow.setTabOrder(self.senha, self.btn_cadastrar)
        MainWindow.setTabOrder(self.btn_cadastrar, self.btn_voltar)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cadastre-se"))
        self.lbl_crie_conta.setText(_translate("MainWindow", "Crie sua conta"))
        self.btn_cadastrar.setText(_translate("MainWindow", "Cadastrar"))
        self.usuario.setPlaceholderText(_translate("MainWindow", "Usuário"))
        self.senha.setPlaceholderText(_translate("MainWindow", "Senha"))
        self.btn_voltar.setText(_translate("MainWindow", "Voltar"))
