# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_logado.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TelaLogado(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(347, 413)
        MainWindow.setMinimumSize(QtCore.QSize(347, 413))
        MainWindow.setMaximumSize(QtCore.QSize(347, 413))
        MainWindow.setStyleSheet("background-color: rgb(57, 130, 195);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_logado = QtWidgets.QLabel(self.centralwidget)
        self.lbl_logado.setGeometry(QtCore.QRect(88, 70, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lbl_logado.setFont(font)
        self.lbl_logado.setStyleSheet("color:white;\n"
"font-size: 24px;")
        self.lbl_logado.setObjectName("lbl_logado")
        self.btn_logout = QtWidgets.QPushButton(self.centralwidget)
        self.btn_logout.setGeometry(QtCore.QRect(121, 190, 120, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_logout.setFont(font)
        self.btn_logout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_logout.setStyleSheet("background-color: rgb(237, 212, 0);\n"
"border-radius: 15px;\n"
"")
        self.btn_logout.setObjectName("btn_logout")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Logado"))
        self.lbl_logado.setText(_translate("MainWindow", "Você está logado!"))
        self.btn_logout.setText(_translate("MainWindow", "LOGOUT"))
