# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Admin(object):
    def setupUi(self, Admin):
        Admin.setObjectName("Admin")
        Admin.resize(347, 387)
        Admin.setMinimumSize(QtCore.QSize(347, 387))
        Admin.setMaximumSize(QtCore.QSize(347, 387))
        Admin.setStyleSheet("background-color: rgb(57, 130, 195);")
        self.centralwidget = QtWidgets.QWidget(Admin)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_logout = QtWidgets.QPushButton(self.centralwidget)
        self.btn_logout.setGeometry(QtCore.QRect(240, 340, 101, 31))
        self.btn_logout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_logout.setStyleSheet("background-color: rgb(237, 212, 0);\n"
"border-radius: 15px;\n"
"")
        self.btn_logout.setDefault(True)
        self.btn_logout.setObjectName("btn_logout")
        self.tbl_usuarios = QtWidgets.QTableWidget(self.centralwidget)
        self.tbl_usuarios.setEnabled(True)
        self.tbl_usuarios.setGeometry(QtCore.QRect(10, 10, 331, 321))
        self.tbl_usuarios.setTabKeyNavigation(False)
        self.tbl_usuarios.setWordWrap(True)
        self.tbl_usuarios.setObjectName("tbl_usuarios")
        self.tbl_usuarios.setColumnCount(3)
        self.tbl_usuarios.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tbl_usuarios.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tbl_usuarios.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tbl_usuarios.setHorizontalHeaderItem(2, item)
        self.btn_excluir = QtWidgets.QPushButton(self.centralwidget)
        self.btn_excluir.setEnabled(True)
        self.btn_excluir.setGeometry(QtCore.QRect(10, 340, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.btn_excluir.setFont(font)
        self.btn_excluir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_excluir.setStyleSheet("background-color: rgb(255, 52, 52);\n"
"border-radius: 15px;\n"
"")
        self.btn_excluir.setCheckable(False)
        self.btn_excluir.setChecked(False)
        self.btn_excluir.setDefault(True)
        self.btn_excluir.setObjectName("btn_excluir")
        self.btn_editar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_editar.setGeometry(QtCore.QRect(124, 340, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.btn_editar.setFont(font)
        self.btn_editar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_editar.setStyleSheet("background-color: #6EC8DB;\n"
"border-radius: 15px;\n"
"")
        self.btn_editar.setDefault(True)
        self.btn_editar.setObjectName("btn_editar")
        Admin.setCentralWidget(self.centralwidget)

        self.retranslateUi(Admin)
        QtCore.QMetaObject.connectSlotsByName(Admin)
        Admin.setTabOrder(self.btn_logout, self.btn_editar)
        Admin.setTabOrder(self.btn_editar, self.btn_excluir)
        Admin.setTabOrder(self.btn_excluir, self.tbl_usuarios)

    def retranslateUi(self, Admin):
        _translate = QtCore.QCoreApplication.translate
        Admin.setWindowTitle(_translate("Admin", "Admin"))
        self.btn_logout.setText(_translate("Admin", "LOGOUT"))
        item = self.tbl_usuarios.horizontalHeaderItem(0)
        item.setText(_translate("Admin", "ID"))
        item = self.tbl_usuarios.horizontalHeaderItem(1)
        item.setText(_translate("Admin", "Usuário"))
        item = self.tbl_usuarios.horizontalHeaderItem(2)
        item.setText(_translate("Admin", "Senha"))
        self.btn_excluir.setText(_translate("Admin", "Excluir"))
        self.btn_editar.setText(_translate("Admin", "Editar"))
