# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(347, 369)
        MainWindow.setMinimumSize(QtCore.QSize(347, 369))
        MainWindow.setMaximumSize(QtCore.QSize(347, 369))
        MainWindow.setStyleSheet("background-color: rgb(57, 130, 195);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_entrar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_entrar.setGeometry(QtCore.QRect(130, 195, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.btn_entrar.setFont(font)
        self.btn_entrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_entrar.setStyleSheet("background-color: #6EC8DB;\n"
"border-radius: 15px;\n"
"color: white")
        self.btn_entrar.setDefault(True)
        self.btn_entrar.setObjectName("btn_entrar")
        self.usuario = QtWidgets.QLineEdit(self.centralwidget)
        self.usuario.setGeometry(QtCore.QRect(90, 65, 191, 31))
        self.usuario.setStyleSheet("background-color: rgb(255,255,255);\n"
"border-radius: 15px;\n"
"padding: 5px;\n"
"padding-left: 7px;")
        self.usuario.setObjectName("usuario")
        self.senha = QtWidgets.QLineEdit(self.centralwidget)
        self.senha.setGeometry(QtCore.QRect(90, 125, 191, 31))
        self.senha.setStyleSheet("background-color: rgb(255,255,255);\n"
"border-radius: 15px;\n"
"padding: 5px;\n"
"padding-left: 7px;")
        self.senha.setObjectName("senha")
        self.lbl_cadastro = QtWidgets.QLabel(self.centralwidget)
        self.lbl_cadastro.setGeometry(QtCore.QRect(138, 295, 91, 17))
        self.lbl_cadastro.setObjectName("lbl_cadastro")
        self.btn_cadastrar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cadastrar.setGeometry(QtCore.QRect(135, 325, 89, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_cadastrar.setFont(font)
        self.btn_cadastrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cadastrar.setStyleSheet("background-color: rgb(237, 212, 0);\n"
"border-radius: 15px;\n"
"")
        self.btn_cadastrar.setObjectName("btn_cadastrar")
        self.lbl_login = QtWidgets.QLabel(self.centralwidget)
        self.lbl_login.setGeometry(QtCore.QRect(110, 15, 161, 31))
        self.lbl_login.setStyleSheet("font-size: 16pt;\n"
"color: white;")
        self.lbl_login.setObjectName("lbl_login")
        self.lbl_erro = QtWidgets.QLabel(self.centralwidget)
        self.lbl_erro.setGeometry(QtCore.QRect(80, 165, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_erro.setFont(font)
        self.lbl_erro.setStyleSheet("color: rgb(237, 212, 0);")
        self.lbl_erro.setText("")
        self.lbl_erro.setObjectName("lbl_erro")
        self.lbl_login_img = QtWidgets.QLabel(self.centralwidget)
        self.lbl_login_img.setGeometry(QtCore.QRect(50, 60, 31, 40))
        self.lbl_login_img.setText("")
        self.lbl_login_img.setPixmap(QtGui.QPixmap("login.png"))
        self.lbl_login_img.setObjectName("lbl_login_img")
        self.lbl_senha_img = QtWidgets.QLabel(self.centralwidget)
        self.lbl_senha_img.setGeometry(QtCore.QRect(50, 120, 31, 40))
        self.lbl_senha_img.setText("")
        self.lbl_senha_img.setPixmap(QtGui.QPixmap("senha.png"))
        self.lbl_senha_img.setObjectName("lbl_senha_img")
        self.senha.setEchoMode(QtWidgets.QLineEdit.Password)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.usuario, self.senha)
        MainWindow.setTabOrder(self.senha, self.btn_entrar)
        MainWindow.setTabOrder(self.btn_entrar, self.btn_cadastrar)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Logon"))
        self.btn_entrar.setText(_translate("MainWindow", "Entrar"))
        self.usuario.setPlaceholderText(_translate("MainWindow", "Usuário"))
        self.senha.setPlaceholderText(_translate("MainWindow", "Senha"))
        self.lbl_cadastro.setText(_translate("MainWindow", "Não é cadastrado?"))
        self.btn_cadastrar.setText(_translate("MainWindow", "Cadastrar"))
        self.lbl_login.setText(_translate("MainWindow", "Faça o seu login"))
